### ISSUE TITLE
Any interest?

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-tubeify#3]
@fatg3erman Any interest in this kind of thing? I made it for myself, but posted up on GitHub if others are interested.

- Tidal doesn't work - don't have an account, and they have CAPTCHA now
- Spotify requires oauth2 details in a file at `/tmp/spotify_creds.json` (`token_url`, `client_id`, `client_secret`).
- Some of the other services are a bit flakey (I think the `kexp` one, in particular, randomly breaks from time to time).
- The track matching can get things wrong; very wrong sometimes.

Anyway, let me know if you're interested/have any suggestions.

**Comment by fatg3erman** [comment]
Cool idea, thanks for sharing. I've never used playlists so it's not something I need.
